#!/usr/bin/env bash

set -e

setup_google_creds() {
    # Create a temporary file
    TEMP_CRED_FILE=$(mktemp --suffix=".json")
    
    # Ensure temporary file is removed on script exit or interrupt
    trap "rm -f $TEMP_CRED_FILE" EXIT
    
    # Write the environment variable content to the temporary file
    echo "${CUSTOM_KEY}" > "$TEMP_CRED_FILE"

    export GOOGLE_APPLICATION_CREDENTIALS=$TEMP_CRED_FILE

}

setup_google_creds

export AWS_REGION=us-west-2

# Parse --mode from named parameters; collect remaining args to forward
MODE="train"
REMAINING_ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)
            MODE="$2"
            shift 2
            ;;
        *)
            REMAINING_ARGS+=("$1")
            shift
            ;;
    esac
done

# Dispatch to the appropriate script
case "$MODE" in
    train)
        python -u train.py "${REMAINING_ARGS[@]}"
        ;;
    evaluate)
        python -u evaluate.py "${REMAINING_ARGS[@]}"
        ;;
    *)
        echo "Invalid mode: '$MODE'. Must be 'train' or 'evaluate'." >&2
        exit 1
        ;;
esac
