#!/usr/bin/env bash
set -e

git clone https://github.com/AllenInstitute/neuron-proofreader.git
cd neuron-proofreader
git checkout 0738122
pip install -e .

git clone https://github.com/AllenNeuralDynamics/neuron-proofreading-evaluation.git
cd neuron-proofreading-evaluation
git checkout 4af4dc6
pip install -e .


